export const prayerCategories = {
  "Santé spirituelle": [
    "Affaiblissement spirituel",
    "Oppression spirituelle",
    "Sécheresse spirituelle",
    "Manque de paix intérieure",
    "Lutte contre le péché",
    "Besoin de délivrance",
    "Combat spirituel",
    "Perte de repères spirituels",
    "Fatigue spirituelle",
    "Guérison intérieure",
    "__OTHER__",
  ],
Foi: [
  "Croissance spirituelle",
  "Relation personnelle avec Dieu",
  "Lecture et compréhension de la Bible",
  "Temps de prière",
  "Discipline spirituelle",
  "Doutes dans la foi",
  "Foi dans l'épreuve",
  "Manque de foi ou de confiance",
  "Retour à Dieu",
  "Obéissance",
  "Vie spirituelle au quotidien",
  "Recherche de sens",
  "__OTHER__",
],
  Famille: [
    "Unité familiale",
    "Conflits",
    "Relations familiales",
    "Éducation des enfants",
    "Protection",
    "Relations parent-enfant",
    "Famille recomposée",
    "Famille brisée",
    "Relations avec les beaux-parents",
    "__OTHER__",
  ],
  "Santé physique": [
    "Guérison physique",
    "Douleurs chroniques",
    "Maladies chroniques",
    "Maladie grave ou incurable",
    "Hospitalisation",
    "Rétablissement après opération",
    "Fatigue intense ou épuisement",
    "Burn-out",
    "Addictions",
    "Troubles du sommeil",
    "Problèmes alimentaires",
    "Handicap ou mobilité réduite",
    "Santé d’un proche",
    "Accompagnement pendant la maladie",
    "Traitement médical en cours",
    "Affaiblissement général",
    "__OTHER__",
  ],
  Relations: [
  "Amitié",
  "Conflits relationnels",
  "Manque de pardon",
  "Trahison",
  "Solitude",
  "Isolement social",
  "Réconciliation",
  "Relations toxiques",
  "Relations brisées",
  "Difficultés de communication",
  "Rupture difficile",
  "Relations familiales compliquées",
  "Relations professionnelles tendues",
  "__OTHER__",
],
  Mariage: [
  "Restauration du couple",
  "Crise conjugale",
  "Manque de communication",
  "Infidélité",
  "Pardon dans le couple",
  "Conflits répétés",
  "Éloignement affectif",
  "Difficultés intimes",
  "Pression extérieure (famille, entourage)",
  "Mariage à venir",
  "Préparation au mariage",
  "Bien vivre son célibat",
  "Désir de fonder une famille",
  "__OTHER__",
],
Ministère: [
  "Appel",
  "Discernement",
  "Confirmation de l’appel",
  "Persévérance",
  "Fatigue dans le ministère",
  "Épreuves dans le ministère",
  "Découragement spirituel",
  "Protection spirituelle",
  "Unité dans l’équipe",
  "Conflits dans l’équipe",
  "Vision et direction",
  "Évangélisation",
  "Leadership",
  "__OTHER__",
],
Travail: [
  "Recherche d'emploi",
  "Orientation professionnelle",
  "Projet professionnel",
  "Blocage professionnel",
  "Pression ou surcharge de travail",
  "Burn-out professionnel",
  "Manque de reconnaissance",
  "Conflits avec collègues",
  "Relations difficiles avec la hiérarchie",
  "Stabilité professionnelle",
  "Changement de carrière",
  "Conditions de travail difficiles",
  "Équilibre vie professionnelle / personnelle",
  "__OTHER__",
],
Finances: [
  "Difficultés financières",
  "Endettement",
  "Gestion du budget",
  "Manque de ressources",
  "Factures impayées",
  "Précarité financière",
  "Projets bloqués par manque d'argent",
  "Recherche de stabilité financière",
  "Soutien pour une cause",
  "Générosité et dons",
  "Bénédictions financières",
  "Sagesse dans la gestion financière",
  "__OTHER__",
],
Émotions: [
  "Dépression",
  "Anxiété",
  "Stress chronique",
  "Colère",
  "Tristesse profonde",
  "Manque d’estime de soi",
  "Peur ou insécurité",
  "Découragement",
  "Culpabilité",
  "Honte",
  "Pardon envers soi-même",
  "Guérison émotionnelle",
  "__OTHER__",
],
  Autres: [],
};
